package org.ntqqrev.acidify.internal.packet.message.elem

import org.ntqqrev.acidify.internal.protobuf.*

internal object NotOnlineImage : PbSchema() {
    val filePath = PbBytes[1]
    val fileLen = PbInt32[2]
    val downloadPath = PbBytes[3]
    val oldVerSendFile = PbBytes[4]
    val imgType = PbInt32[5]
    val previewsImage = PbBytes[6]
    val picMd5 = PbBytes[7]
    val picHeight = PbInt32[8]
    val picWidth = PbInt32[9]
    val resId = PbBytes[10]
    val flag = PbBytes[11]
    val thumbUrl = PbString[12]
    val original = PbInt32[13]
    val bigUrl = PbString[14]
    val origUrl = PbString[15]
    val bizType = PbInt32[16]
    val result = PbInt32[17]
    val index = PbInt32[18]
    val opFaceBuf = PbBytes[19]
    val oldPicMd5 = PbBoolean[20]
    val thumbWidth = PbInt32[21]
    val thumbHeight = PbInt32[22]
    val fileId = PbInt32[23]
    val showLen = PbInt32[24]
    val downloadLen = PbInt32[25]
    val url400 = PbString[26]
    val width400 = PbInt32[27]
    val height400 = PbInt32[28]
    val pbReserve = PbBytes[29]
}